# See more hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
      - id: style-files
        name: Style files using styler
        args: [ --style_pkg=styler, --style_fun=tidyverse_style ]
      - id: roxygenize
        name: Run roxygen2::roxygenize()
      # codemeta must be above use-tidy-description when both are used
      # -   id: codemeta-description-updated
      - id: use-tidy-description
        name: Run sethis::use_tidy_description()
      - id: lintr
        name: Run lintr::lint()
        exclude: renv/activate.R
      - id: readme-rmd-rendered
        name: Check README.Rmd has been rendered to README.md
      - id: parsable-R
        name: Check for valid R code using the parse() function
      - id: no-browser-statement
        name: Check for accidential browser() statements
