project:
  type: website
  output-dir: ../../docs/

website:
  title: Draft Coding in Analysis and Research Survey 2023
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: data_collection.qmd
        text: Data collection
      - href: summary.qmd
        text: Summary statistics
      - href: departments.qmd
        text: Department summaries
      - href: professions.qmd
        text: Profession summaries

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
execute:
  echo: false
  warning: false
