---
title: Department summaries
output:
  html_document
---

[comment]: <> (This document makes use of custom open and close tags for use with glue::glue() (" and ", respectively))
[comment]: <> (This document should only be edited as a template: quarto/templates/departments.qmd)

Below are links to profession-specific reports These contain summary statistics, filtered by department. Only departments with 20 or more respondents are included.

- [Centre for Environment, Fisheries and Aquaculture Science](departments/centre-for-environment-fisheries-and-aquaculture-science.html)

- [Department for Business, Energy and Industrial Strategy (excl. agencies)](departments/department-for-business-energy-and-industrial-strategy-excl-agencies-.html)

- [Department for Digital, Culture, Media and Sport](departments/department-for-digital-culture-media-and-sport.html)

- [Department for Education](departments/department-for-education.html)

- [Department for Environment, Food and Rural Affairs (excl. agencies)](departments/department-for-environment-food-and-rural-affairs-excl-agencies-.html)

- [Department for International Trade](departments/department-for-international-trade.html)

- [Department for Levelling Up, Housing and Communities](departments/department-for-levelling-up-housing-and-communities.html)

- [Department for Transport (excl. agencies)](departments/department-for-transport-excl-agencies-.html)

- [Department for Work and Pensions](departments/department-for-work-and-pensions.html)

- [Department of Health and Social Care (excl. agencies)](departments/department-of-health-and-social-care-excl-agencies-.html)

- [Forestry Commission](departments/forestry-commission.html)

- [Government Actuary's Department](departments/government-actuary-s-department.html)

- [HM Revenue and Customs](departments/hm-revenue-and-customs.html)

- [Ministry of Defence](departments/ministry-of-defence.html)

- [Ministry of Justice (excl. agencies)](departments/ministry-of-justice-excl-agencies-.html)

- [National Records of Scotland](departments/national-records-of-scotland.html)

- [Northern Ireland Statistics and Research Agency](departments/northern-ireland-statistics-and-research-agency.html)

- [Office for National Statistics](departments/office-for-national-statistics.html)

- [Public Health Scotland](departments/public-health-scotland.html)

- [Scottish Government (excl. agencies)](departments/scottish-government-excl-agencies-.html)

- [UK Health Security Agency](departments/uk-health-security-agency.html)

- [Welsh Government](departments/welsh-government.html)


