---
title: "Home"
---

## How do analysts use programming and software engineering in the UK Public Sector?

The Coding in Analysis and Research Survey (CARS) was developed to understand better how government analysts use programming. Most questions focused on whether and how analysts use coding in their work. The survey is also concerned with [Reproducible Analytical Pipelines (RAP)](#rap). 

The survey was distributed to government analysts and researchers in the autumn of 2024. The results presented summarise the key findings from 1300 respondents from over 50 public sector organisations.


## Who is this research for?


This research was made with senior analysts and leaders in mind. It is intended to be be useful for the development of strategies for public sector analysis and research. These findings should also be of interest to analysts and researchers in the public sector who are interested in understanding more about how their professions use programming in their work. Lastly, it will be useful to people outside the public sector who are interested in understanding the tools that are used in the public sector for analysis and research.

## How to use this research


Responding to CARS is voluntary. The results presented here are from a self-selecting sample of government analysts. Because respondents are self-selecting, the results we present only reflect the views of the analysts who participated.

We cannot draw wider conclusions about the general population of government analysts from these results because the survey is not based on a random sample.
 
Do:

* Explore the data to gain insights about current coding practices in government analysis and research
* Re-use the outputs if you wish

Avoid:

* Attempting to estimate absolute frequencies - we did not use random sampling
* Inferring differences between groups - these outputs are only intended to be descriptive and inferential tests were not carried out unless stated otherwise

For more detail, [see the data collection page](data_collection.qmd). 

## More information on reproducible analytical pipelines {#rap}

[The Reproducible Analytical Pipelines Minimum Viable Product](https://github.com/best-practice-and-impact/rap_mvp_maturity_guidance/blob/master/Reproducible-Analytical-Pipelines-MVP.md) sets out the minimum expectations for what analysts must do for work to qualify as a RAP.

[Quality assurance for coding in analysis and research](https://best-practice-and-impact.github.io/qa-of-code-guidance/)

[RAP champions network page](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/reproducible-analytical-pipeline-rap-champions/)


## Accessibility statement

This accessibility statement applies to the Coding in Analysis and Research Survey report. Please note that this does not include third-party content that is referenced from this site.

The website is managed by the Methodology and Quality division of the Office for National Statistics. We would like this guidance to be accessible for as many people as possible. This means that you should be able to:

* change colours, contrast levels and fonts
* zoom in up to 300% without the text spilling off the screen
* navigate most of the website using just a keyboard
* navigate most of the website using speech recognition software
* listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)

### Feedback and reporting accessibility problems

We’re always looking to improve the accessibility of our guidance. If you find any problems not listed on this page or think that we’re not meeting accessibility requirements, please contact us by email at gsshelp@statistics.gov.uk. Please also get in touch if you are unable to access any part of this guidance, or require the content in a different format.

We will consider your request and aim to get back to you within 5 working days.

### Enforcement procedure

The Equality and Human Rights Commission (EHRC) is responsible for enforcing the [Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’)](https://www.legislation.gov.uk/uksi/2018/952/made). If you’re not happy with how we respond to your complaint, you should [contact the Equality Advisory and Support Service (EASS)](https://www.equalityadvisoryservice.com/).

## Contact details

We would like to know what you think of the survey and the outputs. Please contact us if you have feedback on any of the following:

* Outputs/analyses you would like to see added to this research
* Information you would like to see collected in the next iteration of CARS
* Any other comments

If you are interested in this survey or any of the questions asked, or want to give feedback, please contact ASAP@ONS.gov.uk.
