---
title: Profession summaries
output:
  html_document
---

[comment]: <> (This document makes use of custom open and close tags for use with glue::glue() (" and ", respectively))
[comment]: <> (This document should only be edited as a template: quarto/templates/professions.qmd)

:::{.callout-note}
Please note, these are the initial summary statistics for CARS 2023 and further analysis will follow. 
We advise linking directly to this document when distributing to ensure the most up to date information.
:::

Below are links to profession-specific reports These contain summary statistics, filtered by profession. Only professions with 20 or more respondents are included.

- [Data Scientists](professions/data-scientists.html)

- [Government Digital and Data](professions/government-digital-and-data.html)

- [Government Economic Service](professions/government-economic-service.html)

- [Government Geography Profession](professions/government-geography-profession.html)

- [Government Operational Research Service](professions/government-operational-research-service.html)

- [Government Science & Engineering](professions/government-science-&-engineering.html)

- [Government Social Research](professions/government-social-research.html)

- [Government Statistician Group](professions/government-statistician-group.html)


