create_dummy_data <- function(type = c("test", "clean")){

  set.seed(100)

  cars_dummy_data <- tibble(UserID = c(NA,
                                       NA,
                                       100000000:100000499),
                            UserNo = c(NA,
                                       NA,
                                       1:500),
                            Name = c(NA),
                            Email = c(NA),
                            IP = c(NA,
                                   NA,
                                   rep("100.00.000.00", 500)),
                            ID = c(NA),
                            Started = c(NA,
                                        NA,
                                        sample(seq(as.POSIXct('2023/10/16'),
                                                   as.POSIXct('2023/11/16'),
                                                   by="15 mins"),
                                               500)),
                            Ended = c(NA,
                                      NA,
                                      sample(seq(as.POSIXct('2023/10/16'),
                                                 as.POSIXct('2023/11/16'),
                                                 by="15 mins"),
                                             500)),
                            Tracking = c(NA,
                                         NA,
                                         sample(tracking_list,
                                                500,
                                                replace = TRUE)),
                            Q1 = c(NA,
                                   NA,
                                   sample(q1_options,
                                          500,
                                          prob = (c(0.8, 0.19, 0.01)),
                                          replace = TRUE))) %>%
    mutate(Q2 = case_when(Q1 == "Civil service, including devolved administrations" ~ sample_replace(q2_options),
                          TRUE ~ NA),
           Q3 = case_when(row_number() == 1 ~ "Answer",
                          Q1 == "Civil service, including devolved administrations" ~ sample_replace(q3_options),
                          TRUE ~ NA),
           Q3.1 = case_when(Q3 == NA ~ "some text",
                            Q3 == "Answer" ~ "Other (please specify)",
                            TRUE ~ NA),
           Q4.1 = case_when(row_number() == 1 ~ "Q4.1. Data Engineer (any profession)",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.2 = case_when(row_number() == 1 ~ "Q4.2. Data Scientist (any profession)",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.3 = case_when(row_number() == 1 ~ "Q4.3. Digital, Data and Technology Profession",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.4 = case_when(row_number() == 1 ~ "Q4.4. Government Actuary's Department",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.5 = case_when(row_number() == 1 ~ "Q4.5. Government Economic Service",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.6 = case_when(row_number() == 1 ~ "Q4.6. Government Geography Profession",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.7 = case_when(row_number() == 1 ~ "Q4.7. Government Operational Research Service",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.8 = case_when(row_number() == 1 ~ "Q4.8. Government Social Research",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.9 = case_when(row_number() == 1 ~ "Q4.9. Government Statistician Group",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.10 = case_when(row_number() == 1 ~ "Q4.10. Civil Service, no profession membership",
                             Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q4.11 = case_when(row_number() == 1 ~ "Q4.11. Other Civil Service profession",
                             Q1 == "Civil service, including devolved administrations" ~ sample_replace(yes_no)),
           Q5 = case_when(Q3 == "Office for National Statistics" ~ sample_replace(q5_options)),
           Q6 = case_when(Q1 == "NHS or local healthcare service" ~ sample_replace(q6_options, prob = c(0.9, 0.09, 0.01)),
                          TRUE ~ NA),
           Q7 = case_when(Q6 == "NHS" ~ sample_replace(q7_options),
                          TRUE ~ NA),
           Q8 = case_when(Q6 == "Local Authority or NJC" ~ sample_replace(q7_options),
                          TRUE ~ NA),
           Q9 = case_when(Q1 == "NHS or local healthcare service" ~ sample_replace(q9_options),
                          TRUE ~ NA),
           Q10 = case_when(Q9 == "England"  ~ sample_replace(q10_options),
                           TRUE ~ NA),
           Q11 = case_when(Q9 == "Scotland"  ~ sample_replace(q11_options),
                           TRUE ~ NA),
           Q12 = case_when(Q9 == "Wales"  ~ sample_replace(q12_options),
                           TRUE ~ NA),
           Q13 = case_when(Q9 == "Northern Ireland"  ~ sample_replace(q13_options),
                           TRUE ~ NA),
           Q14 = c(NA, NA, sample(q14_options,
                                 500,
                                 replace = TRUE)),
           Q15 = case_when(Q14 != "Any other qualification"  ~ sample_replace(subject_options),
                           TRUE ~ NA),
           Q16 = case_when(!is.na(Q15)  ~ sample_replace(level_options),
                           TRUE ~ NA),
           Q17 = case_when(!is.na(Q15)  ~ sample_replace(yes_no),
                           TRUE ~ NA),
           Q18 = case_when(Q14 != "Any other qualification"  ~ sample_replace(c(subject_options, NA)),
                           TRUE ~ NA),
           Q19 = case_when(!is.na(Q18)  ~ sample_replace(level_options),
                           TRUE ~ NA),
           Q20 = case_when(!is.na(Q18)  ~ sample_replace(yes_no),
                           TRUE ~ NA),
           Q21 = case_when(Q14 != "Any other qualification" & !is.na(Q18) ~ sample_replace(c(subject_options, NA)),
                           TRUE ~ NA),
           Q22 = case_when(!is.na(Q21)  ~ sample_replace(level_options),
                           TRUE ~ NA),
           Q23 = case_when(!is.na(Q21)  ~ sample_replace(yes_no),
                           TRUE ~ NA),
           Q24 = c(NA, NA, sample(freq_options,
                                  500,
                                  replace = TRUE)),
           Q25 = c(NA, NA, sample(q25_options,
                                  500,
                                  replace = TRUE)),
           Q26.1 = c("Q26.1. Matlab", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.2 = c("Q26.2. Python", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.3 = c("Q26.3. R", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.4 = c("Q26.4. SAS", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.5 = c("Q26.5. SPSS", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.6 = c("Q26.6. SQL", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.7 = c("Q26.7. Stata", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.8 = c("Q26.8. VBA", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.9 = c("Q26.9. Other open source tool (please specify)", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q26.10 = c("Q26.10. Other license/closed source tool (please specify)", 
                      NA, 
                      sample_replace_500(yes_no_dk)),
           Q26.11 = c("Q26.11. Other (please specify the tool and if it available to use for your work):", 
                      NA, sample_replace_500(c(NA,
                                               "some text"),
                                               prob = c(0.8, 0.2))),
           Q27.1 = c("Q27.1. Matlab", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.2 = c("Q27.2. Python", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.3 = c("Q27.3. R", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.4 = c("Q27.4. SAS", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.5 = c("Q27.5. SPSS", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.6 = c("Q27.6. SQL", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.7 = c("Q27.7. Stata", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.8 = c("Q27.8. VBA", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.9 = c("Q27.9. Other open source tool (please specify)", 
                     NA, 
                     sample_replace_500(yes_no_dk)),
           Q27.10 = c("Q27.10. Other license/closed source tool (please specify)", 
                      NA, 
                      sample_replace_500(yes_no_dk)),
           Q27.11 = c("Q27.11. Other (please specify the tool and if it available to use for your work):", 
                      NA, 
                      sample_replace_500(c(NA,
                                           "some text"),
                                           prob = c(0.8, 0.2))),
           Q28 = c(NA, NA, sample_replace_500(yes_no_dk)),
           Q29 = c(NA, NA, sample_replace_500(yes_no_dk)),
           Q30 = case_when(Q24 != "Never" ~ sample_replace(yes_no)),
           Q31 = case_when(Q24 != "Never" & Q30 == "Yes" ~ sample_replace(q31_options)),
           Q32 = case_when(Q24 != "Never" & Q30 == "Yes" ~ sample_replace(q32_options)),
           Q33 = case_when(Q24 != "Never" ~ sample_replace(yes_no)),
           Q34 = case_when(Q33 != "No" ~ sample_replace(yes_no_dk)),
           Q35 = case_when(Q34 == "Yes" ~ sample_replace(q35_options)),
           Q36 = case_when(Q33 != "No" ~ sample_replace(q36_options)))

  q37 <- paste0("Q", seq(37.1, 37.8, 0.1))
  cars_dummy_data[, q37] <- NA

  q38 <- paste0("Q", seq(38.01, 38.13, 0.01))
  cars_dummy_data[, q38] <- NA
  
  q39 <- paste0("Q", seq(39.1, 39.8, 0.1)) 
  cars_dummy_data[, q39] <- NA
  
  q40 <- paste0("Q", 40:42)
  cars_dummy_data[, q40] <- NA
  
  cars_dummy_data <- cars_dummy_data %>% mutate(across(all_of(q37),
                                                     ~ case_when(Q24 != "Never" & Q33 == "Yes" ~ sample_replace(likert),
                                                                 TRUE ~ NA))
  ) %>%
  mutate(across(all_of(q38),
              ~ case_when(Q24 != "Never" ~ sample_replace(q38_options),
                          TRUE ~ NA))
  ) %>%
  mutate(across(all_of(q39),
              ~ case_when(Q24 != "Never" ~ sample_replace(q38_options),
                          TRUE ~ NA))
  ) %>% 
  mutate(across(all_of(q40),
             ~ case_when(Q24 != "Never" ~ sample_replace(yes_no_dk),
                         TRUE ~ NA))
) 

q43 <- paste0("Q", 43:46)
cars_dummy_data[, q43] <- c(NA,
                   NA,
                   sample(c("some text", NA),
                          500,
                          replace = TRUE))

  
  if(type == "test"){
    cars_dummy_data <- cars_dummy_data %>% mutate(across(c(Q1:Q3,
                                                           Q4.1:Q17,
                                                           Q26.1:Q26.10,
                                                           Q27.1:Q27.10,
                                                           Q28:Q37.7,
                                                           Q38.1:Q39.7,
                                                           Q40:Q42), ~ case_when(row_number() %in% c(3:23) ~ tidyr::replace_na(., "test"),
                                                                                                    TRUE ~ .)))
  }

  return(cars_dummy_data)
}







