## code to prepare `generate_dummy_data` dataset goes here

library(dplyr)
library(purrr)
library(usethis)

sample_replace <- purrr::partial(sample, size = 502, replace = TRUE)

sample_replace_500 <- purrr::partial(sample, size = 500, replace = TRUE)

config <- yaml::read_yaml("./config.yml")

create_dummy_data <- function(type = c("test", "clean")){

  set.seed(555)

  cars_dummy_data <- dplyr::tibble(UserID = c(NA,
                                       NA,
                                       100000000:100000499),
                            UserNo = c(NA,
                                       NA,
                                       1:500),
                            Name = c(NA),
                            Email = c(NA),
                            `IP Address` = c(NA,
                                             NA,
                                             rep("100.00.000.00", 500)),
                            `Unique ID` = c(NA),
                            Started = c(NA,
                                        NA,
                                        sample(seq(as.POSIXct('2023/10/16'),
                                                   as.POSIXct('2023/11/16'),
                                                   by="15 mins"),
                                               500)),
                            Ended = c(NA,
                                      NA,
                                      sample(seq(as.POSIXct('2023/10/16'),
                                                 as.POSIXct('2023/11/16'),
                                                 by="15 mins"),
                                             500)),
                            Tracking = c(NA,
                                         NA,
                                         sample(names(config[["tracking_link"]]),
                                                500,
                                                replace = TRUE)),
                            Q1 = c(NA,
                                   NA,
                                   sample(config[["workplace"]][["levels"]],
                                          500,
                                          prob = (c(0.8, 0.19, 0.01)),
                                          replace = TRUE))) %>%
    dplyr::mutate(Q2 = dplyr::case_when(Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["cs_grade"]][["levels"]]),
                          TRUE ~ NA),
           Q3 = dplyr::case_when(dplyr::row_number() == 1 ~ "Answer",
                          Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["department"]][["levels"]]),
                          TRUE ~ NA),
           Q3.1 = dplyr::case_when(Q3 == NA ~ "some text",
                            Q3 == "Answer" ~ "Other (please specify)",
                            TRUE ~ NA),
           Q4.1 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.1. Data Engineer (any profession)",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.2 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.2. Data Scientist (any profession)",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.3 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.3. Digital, Data and Technology Profession",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.4 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.4. Government Actuary's Department",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.5 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.5. Government Economic Service",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.6 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.6. Government Geography Profession",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.7 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.7. Government Operational Research Service",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.8 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.8. Government Science & Engineering",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.9 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.9. Government Social Research",
                            Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.10 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.10. Government Statistician Group",
                             Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.11 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.11. Civil Service, no profession membership",
                             Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q4.12 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q4.12. Other Civil Service profession",
                             Q1 == "Civil service, including devolved administrations" ~ sample_replace(config[["professions"]][["levels"]])),
           Q5 = dplyr::if_else(Q3 == "Office for National Statistics",
                        sample_replace(config[["ons_directorate"]][["levels"]]),
                        NA),
           Q6 = dplyr::if_else(Q1 == "NHS or local healthcare service",
                        sample_replace(config[["pay_band"]][["levels"]], prob = c(0.9, 0.09, 0.01)),
                        NA),
           Q7 = dplyr::if_else(Q6 == "NHS",sample_replace(config[["nhs_band"]][["levels"]]),
                        NA),
           Q8 = dplyr::if_else(Q6 == "Local Authority or NJC",
                        sample_replace(config[["njc_grade"]][["levels"]]),
                        NA),
           Q9 = c(NA, NA, sample(config[["role_duration"]][["levels"]], 500, replace = TRUE)),
           Q10 = c(NA, NA, sample(config[["coding_exp"]][["levels"]], 500, replace = TRUE)),
           Q11 = c(NA, NA, sample(config[["team"]][["levels"]], 500, replace = TRUE)),
           Q12 = c(NA, NA, sample(config[["project_manage"]][["levels"]], 500, replace = TRUE)),
           Q13 = dplyr::if_else(Q10 == "No",
                         sample_replace(config[["code_learn"]][["levels"]]),
                         NA),
           Q14 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q14.1",
                                  Q10 != "No" ~ sample_replace(config[["learn_barriers"]][["levels"]])),
           Q15 = dplyr::if_else(Q10 != "No",
                         sample_replace(config[["coding_years"]][["levels"]]),
                         NA),
           Q16 = dplyr::if_else(Q10 != "No",
                         sample_replace(config[["coding_freq"]][["levels"]]),
                         NA),
           Q17 = dplyr::if_else(Q10 != "No",
                         sample_replace(config[["code_freq_pref"]][["levels"]]),
                         NA),
           Q18 = dplyr::if_else(Q10 != "No",
                                sample_replace(config[["ability_change"]][["levels"]]),
                                NA),
           Q19 = dplyr::case_when(dplyr::row_number() == 1 ~ "Q19.1",
                                  Q10 != "No" ~ sample_replace(config[["improve_barriers"]][["levels"]])),
           Q20 = dplyr::case_when(row_number() == 1 ~ "Q22.1. Python",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.2 = case_when(row_number() == 1 ~ "Q22.2. R",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.3 = case_when(row_number() == 1 ~ "Q22.3. Matlab",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.4 = case_when(row_number() == 1 ~ "Q22.4. SAS",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.5 = case_when(row_number() == 1 ~ "Q22.5. SPSS",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.6 = case_when(row_number() == 1 ~ "Q22.6. SQL",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.7 = case_when(row_number() == 1 ~ "Q22.7. Stata",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.8 = case_when(row_number() == 1 ~ "Q22.8. VBA",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.9 = case_when(row_number() == 1 ~ "Q22.9. Git",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_access"]][["levels"]])),
           Q22.10 = case_when(row_number() == 1 ~ "Q22.10. Other (please specify):",
                              Q14 != "No" ~ sample_replace(c(NA, "some text"), prob = c(0.8, 0.2))),
           Q23.1 = case_when(row_number() == 1 ~ "Q23.1. Python",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.2 = case_when(row_number() == 1 ~ "Q23.2. R",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.3 = case_when(row_number() == 1 ~ "Q23.3. Matlab",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.4 = case_when(row_number() == 1 ~ "Q23.4. SAS",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.5 = case_when(row_number() == 1 ~ "Q23.5. SPSS",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.6 = case_when(row_number() == 1 ~ "Q23.6. SQL",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.7 = case_when(row_number() == 1 ~ "Q23.7. Stata",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.8 = case_when(row_number() == 1 ~ "Q23.8. VBA",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.9 = case_when(row_number() == 1 ~ "Q23.9. Git",
                             Q14 != "No" ~ sample_replace(config[["coding_tools_knowledge"]][["levels"]])),
           Q23.10 = case_when(row_number() == 1 ~ "Q23.10. Other (please specify):",
                              Q14 != "No" ~ sample_replace(c(NA, "some text"), prob = c(0.8, 0.2)))
    )

  Q24 <- paste0("Q", seq(24.1, 24.8, 0.1))
  cars_dummy_data[, Q24] <- NA

  Q25 <- paste0("Q", seq(25.1, 25.6, 0.1))
  cars_dummy_data[, Q25] <- NA

  Q26 <- paste0("Q", seq(26.1, 26.5, 0.1))
  cars_dummy_data[, Q26] <- NA

  cars_dummy_data <- cars_dummy_data %>%
    mutate(across(all_of(c(Q24, Q25, Q26)), ~ case_when(Q14 != "No" & Q17 != "Never" ~ sample_replace(config[["coding_practices"]][["levels"]]),
                                                        TRUE ~ NA)),
           Q27 = if_else(Q17 != "Never",
                         sample_replace(config[["ai"]][["levels"]]),
                         NA),
           Q28.1 = case_when(row_number() == 1 ~ "Q28.1",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q28.2 = case_when(row_number() == 1 ~ "Q28.2",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q28.3 = case_when(row_number() == 1 ~ "Q28.3",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q28.4 = case_when(row_number() == 1 ~ "Q28.4",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q28.5 = case_when(row_number() == 1 ~ "Q28.5",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q28.6 = case_when(row_number() == 1 ~ "Q28.6",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.1 = case_when(row_number() == 1 ~ "Q29.1",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.2 = case_when(row_number() == 1 ~ "Q29.2",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.3 = case_when(row_number() == 1 ~ "Q29.3",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.4 = case_when(row_number() == 1 ~ "Q29.4",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.5 = case_when(row_number() == 1 ~ "Q29.5",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.6 = case_when(row_number() == 1 ~ "Q29.6",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.7 = case_when(row_number() == 1 ~ "Q29.7",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.8 = case_when(row_number() == 1 ~ "Q29.8",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q29.9 = case_when(row_number() == 1 ~ "Q29.9",
                             Q14 != "No" & Q17 != "Never" & Q27 != "No" ~ sample_replace(config[["ai_tools"]][["levels"]])),
           Q30 = if_else(Q14 != "No" & Q17 != "Never" & Q27 != "No",
                         sample_replace(config[["ai_trust"]][["levels"]]),
                         NA),
           Q31 = sample_replace(config[["heard_of_rap"]][["levels"]]),
           Q32.1 = case_when(row_number() == 1 ~ "Q32.1",
                             Q31 != "No" ~ sample_replace(config[["rap_opinions"]][["levels"]])),
           Q32.2 = case_when(row_number() == 1 ~ "Q32.2",
                             Q31 != "No" ~ sample_replace(config[["rap_opinions"]][["levels"]])),
           Q32.3 = case_when(row_number() == 1 ~ "Q32.3",
                             Q31 != "No" ~ sample_replace(config[["rap_opinions"]][["levels"]])),
           Q32.4 = case_when(row_number() == 1 ~ "Q32.4",
                             Q31 != "No" ~ sample_replace(config[["rap_opinions"]][["levels"]])),
           Q32.5 = case_when(row_number() == 1 ~ "Q32.5",
                             Q31 != "No" ~ sample_replace(c(NA, "some text"), prob = c(0.8, 0.2))),
           Q33 = if_else(Q3 == "Office for National Statistics",
                         sample_replace(config[["qs_aware"]][["levels"]]),
                         NA),
           Q34 = if_else(Q3 == "Office for National Statistics",
                         sample_replace(config[["qs_comply"]][["levels"]]),
                         NA),
           Q35 = if_else(Q3 == "Office for National Statistics",
                         sample_replace(config[["qq_aware"]][["levels"]]),
                         NA),
           Q36 = sample_replace(c(NA, "some text"), prob = c(0.8, 0.2)),
           Q37 = sample_replace(c(NA, "some text"), prob = c(0.8, 0.2))

    )


  if(type == "test"){
    cars_dummy_data <- cars_dummy_data %>% mutate(across(c(Q1:Q3,
                                                           Q4.1:Q13,
                                                           Q17:Q22.9,
                                                           Q23.1:Q23.9,
                                                           Q24.1:Q32.4,
                                                           Q33:Q35), ~ case_when(row_number() %in% c(3:500) ~ tidyr::replace_na(., "test"),
                                                                                 TRUE ~ .)))
  }

  return(cars_dummy_data)
}


cars_dummy_data <- create_dummy_data(type = "test")
cars_dummy_data_clean <- create_dummy_data(type = "clean")

usethis::use_data(cars_dummy_data, cars_dummy_data_clean, config, internal = TRUE, overwrite = TRUE)


