rename_dict:

  meta:
    "UserID": "UserID"
    "UserNo": "ID"
    "Name": "Name"
    "Email": "Email"
    "IP.Address::": "IP.Address"
    "Unique.ID": "Unique.ID"
    "Started::": "Started"
    "Ended::": "Ended"
    "Tracking.Link::": "tracking_link"

  demographics:
    "Q1..Where.do.you.primarily.work.::": "workplace"
    "Q2..What.is.your.civil.service.grade.::": "cs_grade"
    "Q3..Which.Civil.Service.department.do.you.primarily.work.in.:Answer:": "department"
    "X:Other (please specify):": "department_other"
    "Q5..Which.ONS.directorate.do.you.belong.to.::": "ons_directorate"
    "Q6..Which.pay.bands.cover.your.role.::": "pay_band"
    "Q7..What.is.your.NHS.band..or.equivalent..::": "nhs_band"
    "Q8..What.is.your.local.authority.or.NJC.grade..or.equivalent..::": "njc_grade"
    "Q9..How.long.have.you.been.in.your.current.role.::": "time_in_role"

  professions:
    "Q4..Do.you.belong.to.any.of.these.civil.service.professions..Tick.all.that.apply.:Q4.1. Data Engineer (any profession):": "prof_DE"
    "Q4.2. Data Scientist (any profession):": "prof_DS"
    "Q4.3. Government Digital and Data:": "prof_GDD"
    "Q4.4. Government Actuary's Department:": "prof_GAD"
    "Q4.5. Government Economic Service:": "prof_GES"
    "Q4.6. Government Geography Profession:": "prof_geog"
    "Q4.7. Government Operational Research Service:": "prof_GORS"
    "Q4.8. Government Science & Engineering:": "prof_GSE"
    "Q4.9. Government Social Research:": "prof_GSR"
    "Q4.10. Government Statistician Group:": "prof_GSG"
    "Q4.11. Civil Service, no profession membership:": "prof_none"
    "Q4.12. Other Civil Service profession:": "prof_other"

  coding_core:
    "Q10..Do.you.have.any.coding.experience.Any.language..past.or.present..inside.or.outside.of.work::": "coding_exp"
    "Q11..Do.you.regularly.work.with.people.who.write.code.to.complete.their.work.::": "team"
    "Q12..Would.you.feel.confident.managing.a.coding.project.::": "manage_project"
    "Q13..Would.you.like.to.use.coding.in.your.current.role.::": "coding_learn_pref"
    "Q15..How.many.years.of.professional.coding.experience.do.you.have.Excluding.any.years.in.education..but.including.any.previous.employment::": "coding_years"
    "Q16..In.your.current.role..how.often.do.you.write.code.to.complete.your.work.objectives.::": "code_freq"
    "Q17..Would.you.prefer.to.use.more.coding.in.your.role.::": "coding_freq_pref"
    "Q18..How.has.your.coding.ability.changed.during.your.current.role.::": "ability_change"

  coding_learn_barriers:
    "Q14..What.are.the.barriers..if.any..to.you.learning.to.code.in.your.current.role..Please.select.all.that.apply:Q14.1. Availability of learning and development resources:": "learn_avail_resource"
    "Q14.2. Suitability of learning and development resources:": "learn_suit_resources"
    "Q14.3. Lack of opportunity to practice skills:": "learn_opportunity"
    "Q14.4. Availability of software and tools:": "learn_tools"
    "Q14.5. Lack of management support:": "learn_manager_support"
    "Q14.6. Lack of peer support (people to ask for help):": "learn_peer_support"
    "Q14.7. No barriers / not applicable:": "learn_no_barrier"
    "Q14.8. Other (please specify)::": "learn_other_barrier"

  coding_improve_barriers:
    "Q19..What.are.the.barriers..if.any..to.improving.your.coding.skills.in.your.current.role..Please.select.all.that.apply:Q19.1. Availability of learning and development resources:": "improve_avail_resources"
    "Q19.2. Suitability of learning and development resources:": "improve_suit_resources"
    "Q19.3. Lack of opportunity to practice skills:": "improve_opportunity"
    "Q19.4. Availability of software and tools:": "improve_tools"
    "Q19.5. Lack of management support:": "improve_manager_support"
    "Q19.6. Lack of peer support (people to ask for help):": "improve_peer_support"
    "Q19.7. No barriers / not applicable:": "improve_no_barrier"
    "Q19.8. Other (please specify)::": "improve_other_barrier"

  coding_tools_knowledge:
    "Q20..Which.of.these.tools.do.you.know.how.to.use..even.if.you.don.t.currently.use.it.for.your.work.:Q20.1. Python:": "knowledge_python"
    "Q20.2. R:": "knowledge_R"
    "Q20.3. DAX:": "knowledge_dax"
    "Q20.4. Matlab:": "knowledge_matlab"
    "Q20.5. SAS:": "knowledge_SAS"
    "Q20.6. SPSS:": "knowledge_SPSS"
    "Q20.7. SQL:": "knowledge_SQL"
    "Q20.8. Stata:": "knowledge_stata"
    "Q20.9. Spark:": "knowledge_spark"
    "Q20.10. VBA:": "knowledge_VBA"
    "Q20.11. None of these:": "knowledge_none"
    "Q20.12. Other (please specify):": "knowledge_other"

  coding_tools_use:
    "Q21..Which.of.these.tools.do.you.use.in.your.current.role..Please.select.all.that.apply:Q21.1. Python:": "use_python"
    "Q21.2. R:": "use_R"
    "Q21.3. DAX:": "use_dax"
    "Q21.4. Matlab:": "use_matlab"
    "Q21.5. SAS:": "use_SAS"
    "Q21.6. SPSS:": "use_SPSS"
    "Q21.7. SQL:": "use_SQL"
    "Q21.8. Stata:": "use_stata"
    "Q21.9. Spark:": "use_spark"
    "Q21.10. VBA:": "use_VBA"
    "Q21.11. None of these:": "use_none"
    "Q21.12. Other (please specify):": "use_other"

  git_cloud:
    "Q22..Do.you.know.how.to.use.Git.::": "git"
    "Q23..Do.you.use.any.cloud.data.platforms.or.services.in.your.current.role..Please.select.all.that.apply.Here.we.are.referring.to.remote.services.accessed.over.the.internet.for.the.purposes.of.working.with.data..such.as.data.storage.and.analysis.software.:Q23.1. Google (e.g. Google Cloud Platform, BigQuery):": "google"
    "Q23.2. Amazon (e.g. AWS, sagemaker):": "amazon"
    "Q23.3. Microsoft (e.g. Azure, Fabric):": "microsoft"
    "Q23.4. Cloudera:": "cloudera"
    "Q23.5. Databricks:": "databricks"
    "Q23.6. I don't use any cloud platforms:": "cloud_none"
    "Q23.7. Other (please specify)::": "cloud_other"

  ai:
    "Q24..Do.you.use.any.AI.assistants.when.coding.at.work.::": "ai"
    "Q25..Which.of.the.following.AI.assistants.do.you.use.when.coding.in.your.current.role.Select.all.that.apply:Q25.1. ChatGPT:": "ai_gpt"
    "Q25.2. GitHub Copilot:": "ai_github"
    "Q25.3. Google Gemini:": "ai_google"
    "Q25.4. Microsoft Copilot:": "ai_microsoft"
    "Q25.5. Claude:": "ai_claude"
    "Q25.6. OpenAI Codex:": "ai_codex"
    "Q25.7. Other (please specify)::": "ai_other"
    "Q26..When.coding.at.work..how.often.do.you.use.AI.assistants.for.the.following.tasks.:Q26.1. Writing code:": "ai_use_write"
    "Q26.2. Debugging code:": "ai_use_debug"
    "Q26.3. Documenting code:": "ai_use_doc"
    "Q26.4. Writing unit tests or other automated tests:": "ai_use_testing"
    "Q26.5. Getting answers to a specific coding question:": "ai_use_question"
    "Q26.6. Learning about new concepts or tools:": "ai_use_learn"
    "Q27..What.impact..if.any..has.AI.had.on.your.coding.at.work...optional.::": "ai_impact"

  coding_practices:
    "Q28..Coding.practicesWhen.coding.in.your.current.role..how.often.do.you.do.the.following.:Q28.1. Use open source software (eg. R/Python/SQL):": "prac_open_source"
    "Q28.2. Use a standard code style (e.g. PEP 8, tidyverse):": "prac_code_style"
    "Q28.3. Write functions to reduce repetition in my code:": "prac_functions"
    "Q28.4. Use control flow to adjust how my code runs (e.g. if statements, for loops) :": "prac_control_flow"
    "Q28.5. Separate settings (e.g. parameters, file paths) from the rest of my code:": "prac_config"
    "Q28.6. Have my code reviewed by a colleague:": "prac_review"
    "Q28.7. Manually test my code throughout development:": "prac_manual_tests"
    "Q28.8. Write automated tests (e.g. unit tests, integration tests, smoke tests):": "prac_auto_tests"

  working_practices:
    "Q29..Working.practicesWhen.coding.in.your.current.role..how.often.do.you.do.the.following.:Q29.1. Use a version control system (e.g. Git):": "work_git"
    "Q29.2. Make sure my code can still be used if I change roles:": "work_succession"
    "Q29.3. Understand the aims and scope of the project before starting:": "work_aims"
    "Q29.4. Understand the roles and responsibilities for everyone on the project:": "work_roles"
    "Q29.5. Publish my code in the open:": "work_publish_code"
    "Q29.6. Make sure my analysis meets existing quality standards:": "work_qa"

  documentation:
    "Q30..DocumentationWhen.coding.in.your.current.role..how.often.do.you.do.the.following.:Q30.1. Create a README file for the project:": "doc_readme"
    "Q30.2. Add function documentation (e.g. docstrings for python, roxygen for R):": "doc_function"
    "Q30.3. Record the packages and programme versions the code depends on:": "doc_dependencies"
    "Q30.4. Document the design of the pipeline:": "doc_design"
    "Q30.5. Record manual quality assurance steps:": "doc_qa"

  rap:
    "Q31..To.what.extent.to.you.agree.with.the.following.statement....I.am.currently.implementing.RAP.in.my.work.::": "rap_implementing"
    "Q32..What..if.any..are.the.main.barriers.to.you.implementing.RAP.in.your.current.role..Select.all.that.apply:Q32.1. Availability of tools or IT infrasturcture:": "rap_tools"
    "Q32.2. Lack of management support:": "rap_management"
    "Q32.3. Current skills:": "rap_skills"
    "Q32.4. Lack of guidance or standards:": "rap_guidance"
    "Q32.5. Not enough time:": "rap_time"
    "Q32.6. Lack of peer support/people to ask:": "rap_peer_support"
    "Q32.7. Work not suited to RAP:": "rap_unsuited"
    "Q32.8. None:": "rap_none"
    "Q32.9. Other:": "rap_other"
    "Q32.10. Please add any additional comments to expand on your answer if you would like:": "rap_barrier_comments"

  standards_quality:
    "Q33..Do.you.work.to.any.analysis.or.coding.quality.standards.::": "standards"
    "Q34..Are.you.aware.of.the..Duck.Book...Quality.Assurance.of.Code.for.Analysis.and.Research..::": "duck_book"
    "Q35..Do.you.or.your.team.use.any.cross.government.or.department.specific.analysis.packages.in.your.work..For.example..R.or.python.packages.that.were.developed.to.help.with.common.analysis.or.data.tasks.in.your.department.or.the.wider.public.sector..Examples.include.splink..govcookiecutter..afcharts.::": "packages"
    "Q36..We.are.aiming.to.collate.a.list.of.packages.that.can.help.with.RAP.implementation.across.government..If.you.know.of.an.open.source.package.created.within.the.Civil.Service.or.NHS.that.may.be.useful.to.other.analysts..please.add.the.GitHub.repository.name.or.link.here...Please.only.link.to.public.repositories.::": "packages_list"
    "Q37..The.ONS.Quality.Standard.for.Analysis.gives.the.minimal.standard.of.quality.expected.for.all.analysis.in.ONS..How.aware..if.at.all..are.you.of.the.Quality.Standard...::": "qs_aware"
    "Q38..Overall..how.does.any.analysis.you.produce.comply.with.the.Quality.Standard..::": "qs_comply"
    "Q39..The.ONS.Quality.Questions.have.been.designed.to.help.analysts.assure.their.work.so.that.it.complies.with.the.ONS.Quality.Standard..Which.statement.best.describes.your.experience.of.the.ONS.Quality.Questions..::": "qq_aware"
    "Q40..Do.you.have.any.further.comments.on.your.experiences.with.coding.in.government.analysis.and.research.::": "comments"
    "Q41...Is.there.anything.you.would.like.to.see.in.future.surveys.::": "future_surveys"
