#' @title Rename columns
#'
#' @description Renames columns and removes unnecessary columns
#'
#' @param data tidy CARS dataset
#'
#' @return data.frame
#'
#' @export

rename_cols <- function(data) {
  if (ncol(data) != 112) {
    stop("Unexpected input: incorrect number of columns. Please use the 2022 CARS dataset.")
  }

  colnames(data)[c(1, 7:ncol(data))] <- c(
    "ID",
    "started",
    "ended",
    "tracking_link",
    "workplace",
    "CS_grade",
    "department",
    "other_department_name",
    "prof_DS",
    "prof_DDAT",
    "prof_GAD",
    "prof_GES",
    "prof_geog",
    "prof_GORS",
    "prof_GSR",
    "prof_GSG",
    "prof_CS_none",
    "prof_CS_other",
    "ONS_directorate",
    "highest_qualification",
    "qual_1_subject",
    "qual_1_level",
    "qual_1_learn_code",
    "qual_2_subject",
    "qual_2_level",
    "qual_2_learn_code",
    "qual_3_subject",
    "qual_3_level",
    "qual_3_learn_code",
    "code_freq",
    "management",
    "ops_analysis",
    "ops_cleaning",
    "ops_linking",
    "ops_transfer_migration",
    "ops_vis",
    "ops_machine_learning",
    "ops_modelling",
    "ops_QA",
    "ops_other",
    "ops_other_name",
    "knowledge_R",
    "access_R",
    "knowledge_SQL",
    "access_SQL",
    "knowledge_SAS",
    "access_SAS",
    "knowledge_VBA",
    "access_VBA",
    "knowledge_python",
    "access_python",
    "knowledge_SPSS",
    "access_SPSS",
    "knowledge_stata",
    "access_stata",
    "knowledge_JS",
    "access_JS",
    "knowledge_java",
    "access_java",
    "knowledge_C",
    "access_C",
    "knowledge_matlab",
    "access_matlab",
    "knowledge_access_other",
    "knowledge_git",
    "access_git",
    "other_coding_experience",
    "coding_ability_change",
    "prev_coding_experience",
    "first_learned",
    "heard_of_RAP",
    "know_RAP_champ",
    "strategy_knowledge",
    "RAP_confident",
    "RAP_supported",
    "RAP_resources",
    "RAP_components",
    "RAP_important",
    "RAP_implementing",
    "RAP_planning",
    "RAP_comments",
    "prac_use_open_source",
    "prac_open_source_own",
    "prac_version_control",
    "prac_review",
    "prac_functions",
    "prac_unit_test",
    "prac_package",
    "prac_dir_structure",
    "prac_style",
    "prac_automated_QA",
    "prac_AQUA_book",
    "doc_comments",
    "doc_functions",
    "doc_readme",
    "doc_desk_notes",
    "doc_registers",
    "doc_AQA_logs",
    "doc_flow_charts",
    "doc_other",
    "CI",
    "dep_management",
    "reproducible_workflow",
    "misc_coding",
    "misc_support",
    "misc_additional_data",
    "misc_other"
  )

  data <- data[!colnames(data) %in% c("UserNo", "Name", "Email", "IP.Address", "Unique.ID")]

  return(data)
}
